spring: 
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-tom-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-tom-test
